#!/bin/env python
# git@github.com:tonnytg/python-howto.git
# Antonio Thomacelli Gomes
# Answer to https://py.checkio.org/mission/non-unique-elements

def checkio(data):
    lista = []
    for line in data:
        if data.count(line) > 1:
            lista.append(line)
    return (lista)  


checkio([1, 2, 3, 1, 3]) == [1, 3, 1, 3]
